### ISSUE TITLE
TODO: add testing - jest + react testing library

### ISSUE THREAD

**Issue by allanRubenstein** [allanRubenstein/nextjs-boilerplate#3]
Add linting, jest, react-testing-library, set up an example test.

**Comment by JacobMGEvans** [comment]
If you are interested we can "Raid" your repository, there would be one big PR from our Organization and we would add React Testing Library to your project. We would need constant contact with a maintainer. Let me know if you are interested, you can read more about what we are doing here: https://github.com/OpenSourceRaidGuild/first-quest

We can also help with #2 as well

**Comment by allanRubenstein** [comment]
> If you are interested we can "Raid" your repository, there would be one big PR from our Organization and we would add React Testing Library to your project. We would need constant contact with a maintainer. Let me know if you are interested, you can read more about what we are doing here: https://github.com/OpenSourceRaidGuild/first-quest
> 
> We can also help with #2 as well

I appreciate the offer, but I want to set these up myself to make sure they meet my personal preferences since this repo is meant to be a way for me to save my personal boilerplate and share it with others.

Good luck with the raids, sounds like a fun idea/project!

**Comment by allanRubenstein** [comment]
Use husky to make a precommit hook that runs tests and checks types on commit

**Comment by allanRubenstein** [comment]
Husky was already added, had to update it.
